import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import PreviewRenderer from '@/components/PreviewRenderer';

export const dynamic = 'force-dynamic';



const Pages = async ({ params }) => {
  const supabase = createServerComponentClient({ cookies });
  const { data } = await supabase.from('pages').select().eq('id', params.id);
  const page = data[0];

  if (!page) {
    return <div>Loading</div>;
  }

  return (
    <div>
      <Head>
        <title>{page?.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex justify-around p-8 mx-auto my-8 bg-white border-b shadow-md sm:rounded-lg dark:bg-gray-800/95 dark:border-gray-700'>
        <div className=''>
          <h1 className='mb-4 text-4xl font-bold font-universHeading'>
            {page?.title}
          </h1>
          <PreviewRenderer data={page.blocks} />
          {/* <pre>{JSON.stringify(page.blocks, null, 2)}</pre> */}
        </div>
      </div>
    </div>
  );
};

export default Pages;
