import Head from 'next/head'
import Image from 'next/image';
import React from 'react'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import EditorPage from '@/app/editor-instance';


const Pages = async ({ params }) => {
  const supabase = createServerComponentClient({ cookies })
  const { data } = await supabase.from('pages').select().eq('id', params.id)
  const page = data[0]

  if (!page) {
    return <div>Loading</div>
  }

  return (
    <div>
      <Head>
        <title>{page?.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex flex-wrap justify-around p-8 mx-auto my-8 bg-white border-b shadow-md sm:rounded-lg dark:bg-gray-800/95 dark:border-gray-700'>
        <div className='w-full'>
          <h1 className='mb-4 font-bold text-8xl font-universHeading'>
            {page?.title}
          </h1>
          {/* <p className='text-gray-400'>{page?.date}</p>
          {page?.author
            ? `<p className='text-gray-400'>From: ${page?.author}</p>`
            : ''} */}

        </div>
        <EditorPage />
        {/* {page?.image ? (
          <div className='pl-4'>
            <Image
              src={page?.image}
              objectFit='cover'
              width={400}
              height={300}
              alt='page Image'
            />
          </div>
        ) : page?.type === 'ceo' ? (
          <div className='pl-4'>
            <Image
              src={'/richard.png'}
              objectFit='cover'
              width={800}
              height={1000}
              alt='CEO Image'
            />
          </div>
        ) : (
          <div className='pl-4'>
            <Image
              src={'/generic-page.png'}
              objectFit='cover'
              width={400}
              height={300}
              alt='page Image'
            />
          </div>
        )} */}
      </div>
    </div>
  )
}

export default Pages
