import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';

export const dynamic = 'force-dynamic';



const Announcement = async ({ params }) => {
  const supabase = createServerComponentClient({ cookies });
  const { data } = await supabase.from('announcements').select().eq('id', params.id);
  const announcement = data[0];


  if (!announcement) {
    return <div>Loading</div>;
  }


  return (
    <div>
      <Head>
        <title>{announcement?.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex justify-around p-8 mx-auto my-8 bg-white border-b shadow-md sm:rounded-lg dark:bg-gray-800/95 dark:border-gray-700'>
        <div className=''>
          <h1 className='mb-4 text-4xl font-bold font-universHeading'>
            {announcement?.title}
          </h1>
          <p className='text-gray-400'>{announcement?.date}</p>
          {announcement?.author
            ? `<p className='text-gray-400'>From: ${announcement?.author}</p>`
            : ''}
          <div
            dangerouslySetInnerHTML={{ __html: announcement?.message }}
            style={{ style }}
          ></div>
        </div>
        {announcement?.image ? (
          <div className='pl-4'>
            <Image
              src={announcement?.image}
              objectFit='cover'
              width={400}
              height={300}
              alt='Announcement Image'
            />
          </div>
        ) : announcement?.type === 'CEO' ? (
          <div className='pl-4 mt-16 max-w-32'>
            <Image
              src={'/richard.png'}
              objectFit='cover'
              width={400}
              height={500}
              alt='CEO Image'
            />
          </div>
        ) : announcement?.type === 'Newsletter' ? (
<div className=""></div>
        ) : (
          <div className='pl-4'>
            <Image
              src={'/generic-announcement.png'}
              objectFit='cover'
              width={400}
              height={300}
              alt='Announcement Image'
            />
          </div>
        )}
      </div>
    </div>
  );
};

export default Announcement;
